# Generated by Django 4.2.6 on 2024-02-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_alter_portfolio_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together=set(),
        ),
    ]
