# Generated by Django 4.2.6 on 2024-02-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_alter_portfolio_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='stock',
            field=models.CharField(max_length=5),
        ),
    ]
