# Generated by Django 4.2.6 on 2024-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_portfolio_average_price_portfolio_total_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_return',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='value',
            field=models.DecimalField(decimal_places=5, max_digits=12),
        ),
    ]
