# Generated by Django 4.2.6 on 2024-04-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0010_portfolio_roi_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='roi_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
