# Generated by Django 5.0.2 on 2024-02-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0002_alter_trade_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trade",
            name="time",
        ),
        migrations.AlterField(
            model_name="trade",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="trade",
            name="stock",
            field=models.CharField(max_length=5),
        ),
    ]
