# Generated by Django 4.2.6 on 2024-03-30 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_alter_trade_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='date',
        ),
    ]
