# Generated by Django 4.2.6 on 2024-03-30 21:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_remove_trade_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trade',
            name='stockvalue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
