# Generated by Django 4.2.6 on 2024-03-30 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_trade_date_trade_stockvalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='stockvalue',
            new_name='value',
        ),
    ]
