# Generated by Django 4.2.6 on 2024-04-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_rename_stockvalue_trade_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='action',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4),
        ),
    ]
