# Generated by Django 5.0.2 on 2024-02-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0003_remove_trade_time_alter_trade_date_alter_trade_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trade",
            name="action",
            field=models.CharField(
                choices=[("BUY", "Buy"), ("BUY", "Sell")], max_length=4
            ),
        ),
    ]
